### ISSUE TITLE
Create a login interface 

### ISSUE THREAD

**Issue by pawarvarad** [pawarvarad/E-commerce-web-development-technology#1]
create a login interface which takes a personal information  such as usernames, passwords etc

**Comment by jayendranar02** [comment]
hi, i am interested in contributing on this issue....

**Comment by jayendranar02** [comment]
ok

**Comment by pawarvarad** [comment]
you can start working on the issue

**Comment by jayendranar02** [comment]
<div id="login">
        <h2>Login</h2>
        <input type="text" id="username" placeholder="Username">
        <input type="password" id="password" placeholder="Password">
        <button id="loginButton">Login</button>
        <div id="loginMessage" style="color: red; display: none;"></div>
    </div>

    <div id="products"></div>
    <div id="cart"></div>
    <button id="checkout">Checkout</button>

**Comment by jayendranar02** [comment]
<div id="login">
        <h2>Login</h2>
        <input type="text" id="username" placeholder="Username">
        <input type="password" id="password" placeholder="Password">
        <button id="loginButton">Login</button>
        <div id="loginMessage" style="color: red; display: none;"></div>
    </div>

    <div id="products"></div>
    <div id="cart"></div>
    <button id="checkout">Checkout</button>

**Comment by jayendranar02** [comment]
i have posted the html login interface and following the whole html code

**Comment by jayendranar02** [comment]
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Colorful Socks E-commerce Platform</title>
    <link rel="stylesheet" href="socks-ecommerce-styles.css">
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            background-color: #f8f9fa;
        }
        h1 {
            text-align: center;
            color: #343a40;
        }
        #login, #products, #cart {
            margin: 20px auto;
            padding: 10px;
            background-color: #fff;
            border: 1px solid #dee2e6;
            border-radius: 5px;
            width: 300px;
        }
        #products {
            display: none; /* Initially hide products */
            flex-wrap: wrap;
            justify-content: space-around;
        }
        .product {
            border: 1px solid #dee2e6;
            border-radius: 5px;
            padding: 10px;
            text-align: center;
            margin: 10px;
            background-color: #fff;
            box-shadow: 0 2px 5px rgba(0,0,0,0.1);
        }
        #checkout {
            display: block;
            margin: 20px auto;
            padding: 10px 20px;
            background-color: #007bff;
            color: white;
            border: none;
            border-radius: 5px;
            cursor: pointer;
        }
        #checkout:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <h1>Colorful Socks E-commerce Platform</h1>
    
    <div id="login">
        <h2>Login</h2>
        <input type="text" id="username" placeholder="Username">
        <input type="password" id="password" placeholder="Password">
        <button id="loginButton">Login</button>
        <div id="loginMessage" style="color: red; display: none;"></div>
    </div>

    <div id="products"></div>
    <div id="cart"></div>
    <button id="checkout">Checkout</button>

    <script>
        const products = [
            { id: 1, name: 'Red Socks', price: 9.99, image: 'images/red-socks.jpg' },
            { id: 2, name: 'Blue Socks', price: 9.99, image: 'images/blue-socks.jpg' },
            { id: 3, name: 'Green Socks', price: 9.99, image: 'images/green-socks.jpg' }
        ];

        let cart = [];
        let loggedIn = false;

        function displayProducts() {
            const productsDiv = document.getElementById('products');
            productsDiv.innerHTML = products.map(product => `
                <div class="product">
                    <img src="${product.image}" alt="${product.name}" style="width: 100%; height: auto;">
                    <h3>${product.name}</h3>
                    <p>Price: $${product.price.toFixed(2)}</p>
                    <button onclick="addToCart(${product.id})">Add to Cart</button>
                </div>
            `).join('');
            productsDiv.style.display = 'flex'; // Show products after login
        }

        function addToCart(productId) {
            const product = products.find(p => p.id === productId);
            cart.push(product);
            updateCart();
        }

        function updateCart() {
            const cartDiv = document.getElementById('cart');
            if (cart.length === 0) {
                cartDiv.innerHTML = `<h2>Shopping Cart is Empty</h2>`;
                return;
            }
            cartDiv.innerHTML = `
                <h2>Shopping Cart</h2>
                ${cart.map(item => `<p>${item.name} - $${item.price.toFixed(2)}</p>`).join('')}
                <p><strong>Total: $${cart.reduce((sum, item) => sum + item.price, 0).toFixed(2)}</strong></p>
            `;
        }

        function checkout() {
            if (cart.length === 0) {
                alert('Your cart is empty!');
            } else {
                const total = cart.reduce((sum, item) => sum + item.price, 0).toFixed(2);
                alert(`Thank you for your purchase! Total: $${total}`);
                cart = [];
                updateCart();
            }
        }

        function login() {
            const username = document.getElementById('username').value;
            const password = document.getElementById('password').value;
            const loginMessage = document.getElementById('loginMessage');

            // Simple login validation (can be expanded)
            if (username === "user" && password === "password") {
                loggedIn = true;
                loginMessage.style.display = 'none';
                document.getElementById('login').style.display = 'none'; // Hide login after successful login
                displayProducts();
            } else {
                loginMessage.innerText = 'Invalid username or password.';
                loginMessage.style.display = 'block';
            }
        }

        document.getElementById('loginButton').addEventListener('click', login);
        document.getElementById('checkout').addEventListener('click', checkout);
    </script>
</body>
</html>

**Comment by jayendranar02** [comment]
ok thanks for contributing on this issue

**Comment by pawarvarad** [comment]
done. thanks for contributing...
